[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/patients-mcp"
  to = "/.netlify/functions/patients-mcp"
  status = 200

[[redirects]]
  from = "/api/patients"
  to = "/.netlify/functions/patients"
  status = 200
